---
title: "Exmple de programmation avec map et variables nommées"
author: "François-Philippe Dubé"
date: "05/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Préparation_exemples}

td <- tibble(
  moyen_orient = rep(c(1, 0), 5),
  droit_pers = rep(c(1, 0), each = 5),
  vote_long = rep(c("Contre", "Pour", "Pour", "Pour", "Contre"), 2), 
  pays = rep(c("CAN", "QC"), each = 5), 
  year = rep(2011:2012, each = 5)
)

enjeux2 <- tibble(court = c("droit_pers", "moyen_orient"))

```

```{r exemple_utilisation_directe_de_fn}

# Fonction avec variable directement passée
fn_prop_enjeux <- function(df, enjeu) {
  df %>%
    group_by(year, pays) %>%
    summarize(
      "prop_{{enjeu}}" := sum((vote_long == "Pour") * {{ enjeu }}) / sum({{ enjeu }})
    )
}

fn_prop_enjeux(td, moyen_orient) # À noter: on ne met pas les var entre guillemets.

```

```{r}

# Fn avec var passée programmatiquement

fn_prop_enjeux2 <- function(df, .enjeu) {
  df %>%
    group_by(year, pays) %>%
    summarize(
      !! sym(str_c("prop_", .enjeu)) := 
        sum((vote_long == "Pour") * !! sym(.enjeu)) / sum(!! sym(.enjeu))
    )
}

map_df(~ fn_prop_enjeux2(td, .enjeu = .x), .x = enjeux2$court)
```

