---
title: "test2"
author: "François-Philippe Dubé"
date: "11/06/2021"
output: html_document
---

```{r definition_tableau_pour_regroupement}
td_long2 <- onu_large %>%
  filter(year > 2014) %>%
  
  # Évite les dédoublements, au cas où il y en aurait
  distinct(resid, pays, vote_long) %>%
 
   # Développe toutes les combinaison pays x resid possibles; introduit des NA
  # dans vote_long où cette combinaison n'existait pas
  complete(pays, nesting(resid)) %>%
  mutate(
    vote_long = replace_na(as.character(vote_long), "na"), # Transforme ces NA en chaînes "na"
    id_vote = str_c("res", resid, vote_long, sep = "_"), # crée un identifiant de vote comme "res_1001_pour"
    valeur = 1 # Cette valeur deviendra notre valeur instrumentale lorsque le tableau sera pivoté
  ) %>%
  
  # On élimine les situations potentielles de vote unanime, peu utiles pour l'algorithme de groupement
  group_by(resid) %>%
  mutate(variations = n_distinct(vote_long)) %>%
  ungroup() %>%
  filter(variations > 1)

td_large_gmm2 <- td_long2 %>%
  pivot_wider(
    id_cols = pays,
    names_from = id_vote,
    values_from = valeur,
    values_fill = 0
  ) %>%
  column_to_rownames("pays") %>%
  select(order(colnames(.))) %>%
  mutate(across(where(is.numeric), ~ as.numeric(scale(.))))
```

```{r regroupements_finaux}
set.seed(420)

gmm_modele2 <- Mclust(td_large_gmm, G = 6)

gmm_res2 <- gmm_modele2 %>% 
  augment(., td_large_gmm) %>% 
  rename(
    pays = .rownames,
    cluster2 = .class
  ) %>%
  select(pays, cluster)
# On recrée un tableau avec les proportions de vote par pays x année, avec les regroupements

onu_final <- onu_large %>%
  filter(year > 2014 & pays != "YUG") %>%
  group_by(pays) %>%
  select(c(pays, starts_with("prop"))) %>%
  rename(prop_total = prop_oui) %>%
  summarize(across(starts_with("prop"), mean)) %>%
  ungroup() %>%
  inner_join(gmm_res2, by = "pays") %>%
  mutate(pays_long = countrycode(pays, origin = "iso3c", destination = "un.name.fr")) %>%
  select(pays_long, pays, cluster, prop_total, everything()) %>% 
  rename(Groupe2 = cluster2)


```

```{r regroupements_phares}
groupe_CAN2 <- onu_final %>%
  filter(pays == "CAN") %>%
  pull(Groupe2)
groupe_CHN2 <- onu_final %>%
  filter(pays == "CHN") %>%
  pull(Groupe2)
groupe_USA2 <- onu_final %>%
  filter(pays == "USA") %>%
  pull(Groupe2)
groupe_FR <- onu_final %>%
  filter(pays == "FRA") %>%
  pull(Groupe2)
```

```{r, fig.height=12, fig.width=8}
enjeux <-
  enjeux %>%
  mutate(var = str_c("prop_", court))

fn_graphe_mclust <- function(.var) {
  .enjeu_long <- enjeux %>%
    filter(var == (.var)) %>%
    pull(long)

  ggplot(data = onu_final, aes(x = prop_total, y = !!sym(.var), colour = Groupe2)) +
    geom_point(size = 2, alpha = 0.6) +
    xlab("Proportion totale de «oui»") +
    ylab("Proportion de «oui» par enjeu") +
    ggtitle(label = sym(.enjeu_long)) +
    scale_y_continuous(
      labels = scales::percent,
      limits = c(0, 1),
      breaks = c(0.25, 0.50, 0.75)
    ) +
    scale_color_brewer(palette = "Set1") +
    theme(legend.position = "bottom") +
    theme(strip.text = element_text(hjust = 0.5)) +
    theme(strip.placement = "inside")
}

graphe_mclust <-
  map(~ fn_graphe_mclust(.var = .x), .x = enjeux$var)

titre <- c("Le Canada pourrait considérer se rapprocher des groupes 2 ou 4 pour gagner en influence")

sous_titre <- paste0(
  "Le Canada est dans le groupe ",
  groupe_CAN,
  ", les É-U, dans le ",
  groupe_USA,
  ", et la Chine dans le ",
  groupe_CHN
)

patchwork::wrap_plots(graphe_mclust, ncol = 2) +
  plot_annotation(title = titre, subtitle = sous_titre) +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")
```
