---
title: "Untitled"
author: "François-Philippe Dubé"
date: "03/05/2021"
output: html_document
---
```{r prep_graphique_par_enjeux, fig.width=6, fig.height=16}
# Définition d'un jeu de données plus restreint
onu_enjeux <- onu_large %>%
  group_by(year = year(date), pays) %>%
  filter(year > 1999 & pays %in% c(g7, "CHN")) %>%
  mutate(prop_oui = mean(vote_long == "Pour")) %>% 
  filter(moyen_orient == 0)


# Définition d'une fonction graphique générique----source:
# https://stackoverflow.com/questions/4856849/looping-over-variables-in-ggplot,
# answered Aug 27 '18 at 19:10 by Tung


fonction_enjeux <- function(df, .enjeu) {
  .enjeu_long <- enjeux %>%
    filter(court == (.enjeu)) %>%
    pull(long)
  df %>%
    filter(!!sym(.enjeu) == 1) %>%
    group_by(year = year(date), pays) %>%
    mutate(prop_oui = mean(vote_long == "Pour")) %>%
    ungroup() %>%
    ggplot(aes(year, prop_oui, colour = pays)) +
    geom_line(size = 0.8, alpha = 0.8) +
    gghighlight(use_direct_label = FALSE) +
    xlab("") +
    ylab("Prop. annuelle de votes 'oui'") +
    ggtitle(label = sym(.enjeu_long)) +
    facet_wrap(~pays, scales = "free_x", ncol = 4, nrow = 2) +
    scale_y_continuous(
      labels = scales::percent,
      limits = c(0, 1),
      breaks = c(0.25, 0.50, 0.75)
    ) +
    theme_few() +
    theme(legend.position = "none") +
    theme(strip.text = element_text(hjust = 0.5)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    theme(strip.placement = "outside")
}

graphes_g7 <- map(~ fonction_enjeux(df = onu_enjeux, .enjeu = .x), .x = enjeux$court[c(2, 3, 4, 5, 7)])
```

```{r graphique_par_enjeux1, fig.width=6, fig.height=14}
graphes_g7

# Premier graphique
patchwork::wrap_plots(graphes_g7[c(3, 2, 6)], ncol = 1) +
  plot_annotation(
    title = "Le Canada appuie particulièrement les initiatives\nde développement économique",
    subtitle = "Il se situe dans la moyenne du G7 sur le désarmement et la question nucélaire"
  )
```


```{r graphique_par_enjeux2, fig.width=6, fig.height=14}

# Deuxième graphique
patchwork::wrap_plots(graphes_g7[c(1, 4, 5)], ncol = 1) +
  plot_annotation(
    title = "À l'autre extrème, le Canada a adopté la position américaine\nsur le Moyen-Orient",
    subtitle = "Il est avec la France sur le colonialisme et avec les É.-U. sur les droits de la personne"
  )
```

